"""
Aureum AI Global Exchange Registry

Central oversigt over alle understøttede børser.
Bruges af Market Session Engine, Portfolio Manager,
AI Copilot, Alerts og øvrige services.
"""

EXCHANGES = {
    "NASDAQ_CPH": {
        "name": "Nasdaq Copenhagen",
        "region": "Europe",
        "country": "Denmark",
        "city": "Copenhagen",
        "timezone": "Europe/Copenhagen",
        "currency": "DKK",
        "suffixes": [".CO"],
        "open": "09:00",
        "close": "17:00",
        "pre_market": False,
        "after_hours": False,
        "weekend": (5, 6),
    },
    "NASDAQ_STO": {
        "name": "Nasdaq Stockholm",
        "region": "Europe",
        "country": "Sweden",
        "city": "Stockholm",
        "timezone": "Europe/Stockholm",
        "currency": "SEK",
        "suffixes": [".ST"],
        "open": "09:00",
        "close": "17:30",
        "pre_market": False,
        "after_hours": False,
        "weekend": (5, 6),
    },
    "OSLO_BORS": {
        "name": "Oslo Børs",
        "region": "Europe",
        "country": "Norway",
        "city": "Oslo",
        "timezone": "Europe/Oslo",
        "currency": "NOK",
        "suffixes": [".OL"],
        "open": "09:00",
        "close": "16:30",
        "pre_market": False,
        "after_hours": False,
        "weekend": (5, 6),
    },
    "EURONEXT_AMS": {
        "name": "Euronext Amsterdam",
        "region": "Europe",
        "country": "Netherlands",
        "city": "Amsterdam",
        "timezone": "Europe/Amsterdam",
        "currency": "EUR",
        "suffixes": [".AS"],
        "open": "09:00",
        "close": "17:30",
        "pre_market": False,
        "after_hours": False,
        "weekend": (5, 6),
    },
    "XETRA": {
        "name": "Xetra",
        "region": "Europe",
        "country": "Germany",
        "city": "Frankfurt",
        "timezone": "Europe/Berlin",
        "currency": "EUR",
        "suffixes": [".DE"],
        "open": "09:00",
        "close": "17:30",
        "pre_market": False,
        "after_hours": False,
        "weekend": (5, 6),
    },
    "EURONEXT_PAR": {
        "name": "Euronext Paris",
        "region": "Europe",
        "country": "France",
        "city": "Paris",
        "timezone": "Europe/Paris",
        "currency": "EUR",
        "suffixes": [".PA"],
        "open": "09:00",
        "close": "17:30",
        "pre_market": False,
        "after_hours": False,
        "weekend": (5, 6),
    },
    "LSE": {
        "name": "London Stock Exchange",
        "region": "Europe",
        "country": "United Kingdom",
        "city": "London",
        "timezone": "Europe/London",
        "currency": "GBP",
        "suffixes": [".L"],
        "open": "08:00",
        "close": "16:30",
        "pre_market": False,
        "after_hours": False,
        "weekend": (5, 6),
    },
    "SIX": {
        "name": "SIX Swiss Exchange",
        "region": "Europe",
        "country": "Switzerland",
        "city": "Zurich",
        "timezone": "Europe/Zurich",
        "currency": "CHF",
        "suffixes": [".SW"],
        "open": "09:00",
        "close": "17:30",
        "pre_market": False,
        "after_hours": False,
        "weekend": (5, 6),
    },
    "BORSA_ITALIANA": {
        "name": "Borsa Italiana",
        "region": "Europe",
        "country": "Italy",
        "city": "Milan",
        "timezone": "Europe/Rome",
        "currency": "EUR",
        "suffixes": [".MI"],
        "open": "09:00",
        "close": "17:30",
        "pre_market": False,
        "after_hours": False,
        "weekend": (5, 6),
    },
    "BME_MADRID": {
        "name": "Bolsa de Madrid",
        "region": "Europe",
        "country": "Spain",
        "city": "Madrid",
        "timezone": "Europe/Madrid",
        "currency": "EUR",
        "suffixes": [".MC"],
        "open": "09:00",
        "close": "17:30",
        "pre_market": False,
        "after_hours": False,
        "weekend": (5, 6),
    },
    "TSE": {
        "name": "Tokyo Stock Exchange",
        "region": "Asia",
        "country": "Japan",
        "city": "Tokyo",
        "timezone": "Asia/Tokyo",
        "currency": "JPY",
        "suffixes": [".T"],
        "open": "09:00",
        "close": "15:30",
        "pre_market": False,
        "after_hours": False,
        "weekend": (5, 6),
    },
    "HKEX": {
        "name": "Hong Kong Exchange",
        "region": "Asia",
        "country": "Hong Kong",
        "city": "Hong Kong",
        "timezone": "Asia/Hong_Kong",
        "currency": "HKD",
        "suffixes": [".HK"],
        "open": "09:30",
        "close": "16:00",
        "pre_market": False,
        "after_hours": False,
        "weekend": (5, 6),
    },
    "SGX": {
        "name": "Singapore Exchange",
        "region": "Asia",
        "country": "Singapore",
        "city": "Singapore",
        "timezone": "Asia/Singapore",
        "currency": "SGD",
        "suffixes": [".SI"],
        "open": "09:00",
        "close": "17:00",
        "pre_market": False,
        "after_hours": False,
        "weekend": (5, 6),
    },
    "ASX": {
        "name": "Australian Securities Exchange",
        "region": "Oceania",
        "country": "Australia",
        "city": "Sydney",
        "timezone": "Australia/Sydney",
        "currency": "AUD",
        "suffixes": [".AX"],
        "open": "10:00",
        "close": "16:00",
        "pre_market": False,
        "after_hours": False,
        "weekend": (5, 6),
    },
    "NSE": {
        "name": "National Stock Exchange India",
        "region": "Asia",
        "country": "India",
        "city": "Mumbai",
        "timezone": "Asia/Kolkata",
        "currency": "INR",
        "suffixes": [".NS"],
        "open": "09:15",
        "close": "15:30",
        "pre_market": True,
        "after_hours": False,
        "weekend": (5, 6),
    },
    "BSE": {
        "name": "Bombay Stock Exchange",
        "region": "Asia",
        "country": "India",
        "city": "Mumbai",
        "timezone": "Asia/Kolkata",
        "currency": "INR",
        "suffixes": [".BO"],
        "open": "09:15",
        "close": "15:30",
        "pre_market": True,
        "after_hours": False,
        "weekend": (5, 6),
    },
    "NASDAQ": {
        "name": "Nasdaq",
        "region": "North America",
        "country": "USA",
        "city": "New York",
        "timezone": "America/New_York",
        "currency": "USD",
        "suffixes": [],
        "open": "09:30",
        "close": "16:00",
        "pre_market": True,
        "after_hours": True,
        "weekend": (5, 6),
    },
    "NYSE": {
        "name": "New York Stock Exchange",
        "region": "North America",
        "country": "USA",
        "city": "New York",
        "timezone": "America/New_York",
        "currency": "USD",
        "suffixes": [],
        "open": "09:30",
        "close": "16:00",
        "pre_market": True,
        "after_hours": True,
        "weekend": (5, 6),
    },
    "TSX": {
        "name": "Toronto Stock Exchange",
        "region": "North America",
        "country": "Canada",
        "city": "Toronto",
        "timezone": "America/Toronto",
        "currency": "CAD",
        "suffixes": [".TO"],
        "open": "09:30",
        "close": "16:00",
        "pre_market": False,
        "after_hours": False,
        "weekend": (5, 6),
    },
    "NASDAQ_HEL": {
        "name": "Nasdaq Helsinki",
        "region": "Europe",
        "country": "Finland",
        "city": "Helsinki",
        "timezone": "Europe/Helsinki",
        "currency": "EUR",
        "suffixes": [".HE"],
        "open": "10:00",
        "close": "18:30",
        "pre_market": False,
        "after_hours": False,
        "weekend": (5, 6),
    },
    "EURONEXT_BRU": {
        "name": "Euronext Brussels",
        "region": "Europe",
        "country": "Belgium",
        "city": "Brussels",
        "timezone": "Europe/Brussels",
        "currency": "EUR",
        "suffixes": [".BR"],
        "open": "09:00",
        "close": "17:30",
        "pre_market": False,
        "after_hours": False,
        "weekend": (5, 6),
    },
    "EURONEXT_DUB": {
        "name": "Euronext Dublin",
        "region": "Europe",
        "country": "Ireland",
        "city": "Dublin",
        "timezone": "Europe/Dublin",
        "currency": "EUR",
        "suffixes": [".IR"],
        "open": "08:00",
        "close": "16:30",
        "pre_market": False,
        "after_hours": False,
        "weekend": (5, 6),
    },
    "EURONEXT_LIS": {
        "name": "Euronext Lisbon",
        "region": "Europe",
        "country": "Portugal",
        "city": "Lisbon",
        "timezone": "Europe/Lisbon",
        "currency": "EUR",
        "suffixes": [".LS"],
        "open": "08:00",
        "close": "16:30",
        "pre_market": False,
        "after_hours": False,
        "weekend": (5, 6),
    },
    "VIENNA": {
        "name": "Vienna Stock Exchange",
        "region": "Europe",
        "country": "Austria",
        "city": "Vienna",
        "timezone": "Europe/Vienna",
        "currency": "EUR",
        "suffixes": [".VI"],
        "open": "09:00",
        "close": "17:30",
        "pre_market": False,
        "after_hours": False,
        "weekend": (5, 6),
    },
    "GPW_WARSAW": {
        "name": "Warsaw Stock Exchange",
        "region": "Europe",
        "country": "Poland",
        "city": "Warsaw",
        "timezone": "Europe/Warsaw",
        "currency": "PLN",
        "suffixes": [".WA"],
        "open": "09:00",
        "close": "16:50",
        "pre_market": False,
        "after_hours": False,
        "weekend": (5, 6),
    },
    "PSE_PRAGUE": {
        "name": "Prague Stock Exchange",
        "region": "Europe",
        "country": "Czech Republic",
        "city": "Prague",
        "timezone": "Europe/Prague",
        "currency": "CZK",
        "suffixes": [".PR"],
        "open": "09:00",
        "close": "16:10",
        "pre_market": False,
        "after_hours": False,
        "weekend": (5, 6),
    },
}

def list_supported_exchanges():
    return sorted(EXCHANGES.keys())


def get_exchange(exchange_id):
    return EXCHANGES.get(exchange_id)
